version: 2.1
jobs:
  frontend:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo/frontend
    steps:
      - checkout:
          path: ~/repo
      - run: npm install
      - run: npm run test
  backend:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo/backend
    steps:
      - checkout:
          path: ~/repo
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  Example_Workflow:
    jobs:
      - frontend
      - backend:
          requires:
            - frontend
